### ISSUE TITLE
Process extension parameters in shortcodes

### ISSUE THREAD

**Issue by prdufresne** [civicrm/civicrm-wordpress#101]
CiviCRM is able to parse and process additional parameters for extensions passed in the URL, for example, when passing a discount code to CiviDiscount. It would be useful if the same provision were made to receive parameters via WordPress shortcodes. For example:

`[civicrm component="contribution" id="2" mode="live" discount="pkpwpabs7" hijack="0"]`

**Comment by totten** [comment]
Thanks for reporting.

It looks some wires got crossed administratively -- Github "Issues" are supposed to be disabled for the main CiviCRM repos (`civicrm-core`, `civicrm-wordpress`, `civicrm-packages`, etal).

If you have a moment, please refile this on http://issues.civicrm.org/
